### ISSUE TITLE
Please tag your release

### ISSUE THREAD

**Issue by ambroisie** [AndrejZbin/django-hcaptcha#11]
The [0.2.0 bump](https://github.com/AndrejZbin/django-hcaptcha/commit/29910669cffe783b2505f842c5da1842bbacd6aa) was not tagged. Could you please tag it?

**Comment by mlissner** [comment]
Looks like it's tagged now. I think this can be closed?

https://github.com/AndrejZbin/django-hcaptcha/commit/29910669cffe783b2505f842c5da1842bbacd6aa
